### ISSUE TITLE
Peer-peer code review.

### ISSUE THREAD

**Issue by kkmanuu** [Yonashenok/Awesome-books#5]
You have done amazing work your code looks clean no Linters problems and you have a  Professional Readme.

**Comment by lily4178993** [comment]
I wanted to take a moment to appreciate the fantastic work you've done on the project 💯 . It's truly impressive! Here are the aspects that stood out to me:

- [x] The UI design looks great. It's visually appealing and user-friendly.

- [x]  The README file is professional and well-structured, providing all the necessary information.

- [x]  You have demonstrated a great understanding of HTML syntax and effectively utilized it in the project.

I do have one minor suggestion to make it even more perfect. In the README, 
- consider adding a link to _[Setup], [Prerequisites], [Install], [Usage], [Run tests]_, and _[Deployment]_
- remove _[Live Demo]_ in your Table of content if you are not planning to add a live demonstration

Keep up the excellent work, and I'm excited to see what you'll accomplish next!
